name: Update Reviews from Google Sheets

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-reviews:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install paramiko requests
    
    - name: Update reviews
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASS: ${{ secrets.FTP_PASS }}
      run: |
        python -c "
        import json
        import paramiko
        import os
        import requests
        import csv
        from io import StringIO
        
        # Stáhni CSV z Google Sheets
        url = 'https://docs.google.com/spreadsheets/d/1hSh2BKVrsvXBpVF4Z5fFoXH2H0vJAqDlqdchDbSz-nk/export?format=csv&gid=0'
        response = requests.get(url)
        
        # Parsuj CSV
        csv_data = csv.reader(StringIO(response.text))
        rows = list(csv_data)
        
        reviews = []
        for row in rows[1:]:  # přeskoč hlavičku
            if len(row) >= 5 and row[0]:
                reviews.append({
                    'code': row[0],
                    'stars': int(row[1]) if row[1].isdigit() else 0,
                    'name': row[2],
                    'source': row[3],
                    'review': row[4]
                })
        
        json_data = json.dumps(reviews, indent=2, ensure_ascii=False)
        
        # Upload přes SFTP
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(os.environ['FTP_HOST'], port=22, username=os.environ['FTP_USER'], password=os.environ['FTP_PASS'])
        
        sftp = ssh.open_sftp()
        with sftp.file('recen.js', 'w') as f:
            f.write(json_data)
        
        sftp.close()
        ssh.close()
        
        print(f'Aktualizováno {len(reviews)} recenzí')
        "
